<div class="card" style="max-width: 800px; margin-top: 20px; padding: 20px;">
    <h3>Import Settings</h3>
    <form id="wpaie-import-form" method="post" enctype="multipart/form-data">
        <?php wp_nonce_field( 'wpaie_import_action', 'wpaie_import_nonce' ); ?>

        <table class="form-table">
            <tr>
                <th scope="row">Import File (.json)</th>
                <td>
                    <input type="file" name="import_file" accept=".json" required>
                    <p class="description">Upload the JSON file generated by this plugin.</p>
                </td>
            </tr>
            <tr>
                <th scope="row">Media Options</th>
                <td>
                    <label>
                        <input type="checkbox" name="download_images" value="1" checked> 
                        Download and import image attachments
                    </label>
                    <p class="description">If checked, the plugin will try to fetch images from the URLs in the export file.</p>
                </td>
            </tr>
            <tr>
                <th scope="row">Content Options</th>
                <td>
                    <label>
                        <input type="checkbox" name="replace_urls" value="1"> 
                        Change all imported URLs that currently link to the previous site so that they now link to this site.
                    </label>
                    <p class="description">Useful when migrating content between domains.</p>
                </td>
            </tr>
            <tr>
                <th scope="row">Author Assignment</th>
                <td>
                    <select name="author_map">
                        <option value="current">Assign to Current Logged-in User</option>
                        <option value="create">Create New Authors (if not exists)</option>
                    </select>
                </td>
            </tr>
        </table>
        
        <div class="wpaie-progress-container">
            <div class="wpaie-status">Ready to import.</div>
            <div class="wpaie-progress-bar">
                <div style="width: 0%;">0%</div>
            </div>
            <div class="wpaie-log-box">
                waiting for input...
            </div>
        </div>

        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="Run Importer">
            <button type="button" id="wpaie-stop-import" class="button button-secondary" style="display:none; margin-left: 10px;">Stop Import</button>
        </p>
    </form>
</div>
